import urllib.parse
from types import SimpleNamespace

from app.core import crypto
from app.core.settings_keys import (
    DRIVE_INBOX_FOLDER_CREATED_BY_APP,
    DRIVE_INBOX_FOLDER_ID,
    DRIVE_INBOX_FOLDER_NAME,
    DRIVE_LIBRARY_FOLDER_CREATED_BY_APP,
    DRIVE_LIBRARY_FOLDER_ID,
    DRIVE_LIBRARY_FOLDER_NAME,
    GOOGLE_OAUTH_SCOPE_MODE,
    GOOGLE_OAUTH_TOKEN_ENC,
)
from app.data.repositories.settings_repository import SettingsRepository
from app.providers.drive.scopes import DRIVE_FILE_SCOPE, DRIVE_SCOPE
from app.services.auth_service import AuthService


def _scope_in_url(url: str) -> str:
    query = urllib.parse.urlparse(url).query
    return urllib.parse.parse_qs(query)["scope"][0]


def test_start_uses_narrow_scope_for_app_created_folder() -> None:
    service = AuthService()
    url = service.start("app_created")
    assert _scope_in_url(url) == DRIVE_FILE_SCOPE


def test_start_uses_broad_scope_for_existing_folder() -> None:
    service = AuthService()
    url = service.start("existing")
    assert _scope_in_url(url) == DRIVE_SCOPE


def test_start_records_pending_state() -> None:
    service = AuthService()
    url = service.start("app_created")
    state = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)["state"][0]
    scope, code_verifier, _ = service._pending_states[state]
    assert scope == DRIVE_FILE_SCOPE
    assert code_verifier  # PKCE verifier must be captured for the token exchange


def test_start_prunes_abandoned_pending_states(monkeypatch) -> None:
    # Regression: a closed tab / abandoned sign-in never calls
    # handle_callback, so nothing else ever pops its _pending_states entry —
    # without pruning, this dict grows without bound over the app's life.
    import app.services.auth_service as auth_module

    service = AuthService()
    clock = [1000.0]
    monkeypatch.setattr(auth_module.time, "monotonic", lambda: clock[0])

    service.start("app_created")
    assert len(service._pending_states) == 1

    clock[0] += auth_module._PENDING_STATE_TTL_SECONDS + 1
    service.start("app_created")

    assert len(service._pending_states) == 1  # the stale entry was pruned, not kept alongside the new one


async def test_handle_callback_reuses_start_code_verifier(db_session, monkeypatch) -> None:
    """Regression test: the PKCE code_verifier generated by start() must be
    the exact one sent during the token exchange in handle_callback(), or
    Google rejects it with 'Missing code verifier'."""
    service = AuthService()
    url = service.start("app_created")
    state = urllib.parse.parse_qs(urllib.parse.urlparse(url).query)["state"][0]
    _, expected_verifier, _ = service._pending_states[state]

    captured: dict[str, str | None] = {}

    class _FakeFlow:
        def __init__(self, code_verifier: str | None) -> None:
            self.code_verifier = code_verifier
            self.credentials = SimpleNamespace(
                token="t",
                refresh_token="r",
                token_uri="https://oauth2.googleapis.com/token",
                scopes=[DRIVE_FILE_SCOPE],
                expiry=None,
            )

        def fetch_token(self, code: str) -> None:
            captured["code_verifier"] = self.code_verifier

    def fake_flow(self, scope: str, code_verifier: str | None = None) -> _FakeFlow:
        return _FakeFlow(code_verifier)

    monkeypatch.setattr(AuthService, "_flow", fake_flow)

    repo = SettingsRepository(db_session)
    await service.handle_callback("dummy-code", state, repo)

    assert captured["code_verifier"] == expected_verifier
    assert expected_verifier is not None


async def test_status_reflects_stored_token(db_session) -> None:
    service = AuthService()
    repo = SettingsRepository(db_session)

    status = await service.status(repo)
    assert status == {"connected": False, "scope_mode": None}

    await repo.set(GOOGLE_OAUTH_TOKEN_ENC, crypto.encrypt("{}"))
    await repo.set(GOOGLE_OAUTH_SCOPE_MODE, DRIVE_SCOPE)

    status = await service.status(repo)
    assert status == {"connected": True, "scope_mode": DRIVE_SCOPE}


async def test_disconnect_clears_stored_token(db_session) -> None:
    service = AuthService()
    repo = SettingsRepository(db_session)
    await repo.set(GOOGLE_OAUTH_TOKEN_ENC, crypto.encrypt("{}"))

    await service.disconnect(repo)

    assert await repo.get(GOOGLE_OAUTH_TOKEN_ENC) is None


async def test_disconnect_clears_folder_selections(db_session) -> None:
    """A stale inbox/library folder from a prior connection must not survive
    a disconnect, or the folder picker shown on reconnect is instantly
    hidden behind the old (wrong) folder."""
    service = AuthService()
    repo = SettingsRepository(db_session)
    await repo.set(GOOGLE_OAUTH_TOKEN_ENC, crypto.encrypt("{}"))
    await repo.set(DRIVE_INBOX_FOLDER_ID, "old-inbox-id")
    await repo.set(DRIVE_INBOX_FOLDER_NAME, "Library")
    await repo.set(DRIVE_INBOX_FOLDER_CREATED_BY_APP, "true")
    await repo.set(DRIVE_LIBRARY_FOLDER_ID, "old-library-id")
    await repo.set(DRIVE_LIBRARY_FOLDER_NAME, "My Library")
    await repo.set(DRIVE_LIBRARY_FOLDER_CREATED_BY_APP, "true")

    await service.disconnect(repo)

    assert await repo.get(DRIVE_INBOX_FOLDER_ID) is None
    assert await repo.get(DRIVE_INBOX_FOLDER_NAME) is None
    assert await repo.get(DRIVE_INBOX_FOLDER_CREATED_BY_APP) is None
    assert await repo.get(DRIVE_LIBRARY_FOLDER_ID) is None
    assert await repo.get(DRIVE_LIBRARY_FOLDER_NAME) is None
    assert await repo.get(DRIVE_LIBRARY_FOLDER_CREATED_BY_APP) is None
