"""add dry_run to operations

Revision ID: e4ef4e5285d7
Revises: a4b6cf91c1a2
Create Date: 2026-08-02 20:53:06.689434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e4ef4e5285d7'
down_revision: Union[str, None] = 'a4b6cf91c1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'operations',
        sa.Column('dry_run', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('operations', 'dry_run')
    # ### end Alembic commands ###
